theme: jekyll-theme-minimal
title: [ERICK_PORTFOLIO]
description: [In 2016 I created my first ecommerce and I had my first contact with Web Analysis. Searching how to bring more users for my website I got to know pay-per-click advertising and I became a Google Partner specialist on it. So, I created the bloco-b that started providing PPC services and web analysis all over Brazil. Now, I am getting into Data Science and Machine Learning looking for better results for the clients of bloco-b.
]
